name: ufl4rom CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 21 * * SAT"
  workflow_dispatch:

jobs:
  test:
    if: >-
      (
        (
          github.event_name == 'schedule'
          && github.repository == 'RBniCS/ufl4rom'
        ) || (
            github.event_name != 'schedule'
            && !(
              contains(github.event.head_commit.message, '[ci skip]')
              || contains(github.event.head_commit.message, '[skip ci]')
            )
        )
      )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup container
        run: |
          export DEBIAN_FRONTEND="noninteractive"
          sudo apt-get -qq update
          sudo apt-get install -qq python3-mpi4py python3-pip
          pip3 -q install pytest pytest-flake8 pytest-xdist
          pip3 -q install git+https://github.com/FEniCS/ufl.git
      - name: Install ufl4rom
        run: |
          python3 setup.py -q install --user
      - name: Run flake8 checks
        run: |
          pytest --flake8 -m flake8
      - name: Run unit tests
        run: |
          pytest -n auto tests/unit
