name: ufl4rom CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 21 * * SAT"
  workflow_dispatch:

jobs:
  test:
    if: >-
      (
        (
          github.event_name == 'schedule'
          && github.repository == 'RBniCS/ufl4rom'
        ) || (
            github.event_name != 'schedule'
            && !(
              contains(github.event.head_commit.message, '[ci skip]')
              || contains(github.event.head_commit.message, '[skip ci]')
            )
        )
      )
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - backend: none
            container: ubuntu
            setup_container: |
              export DEBIAN_FRONTEND="noninteractive"
              apt-get -qq update
              apt-get install -qq git python3-mpi4py python3-pip
              pip3 -q install pytest pytest-flake8 pytest-xdist
              pip3 -q install git+https://github.com/FEniCS/ufl.git
          - backend: dolfin
            container: quay.io/fenicsproject/dev
            setup_container: |
              pip3 -q install --upgrade pytest pytest-flake8 pytest-xdist
          - backend: dolfinx
            container: dolfinx/dolfinx
            setup_container: |
              pip3 -q install --upgrade pytest pytest-flake8 pytest-xdist
          - backend: firedrake
            container: firedrakeproject/firedrake
            setup_container: |
              echo "/home/firedrake/firedrake/bin" >> $GITHUB_PATH
              export PATH=$(cat $GITHUB_PATH):$PATH
              pip3 -q install --upgrade pytest pytest-flake8 pytest-xdist

      fail-fast: false
    container:
      image: ${{ matrix.container }}
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - name: Setup container
        run: ${{ matrix.setup_container }}
      - name: Install ufl4rom
        run: |
          pip3 install .
      - name: Run flake8 checks
        run: |
          pytest --flake8 -m flake8
      - name: Run unit tests
        run: |
          pytest -n auto tests/unit
      - name: Run integration tests
        run: |
          pytest -n auto tests/integration
      - name: Warn if scheduled workflow is about to be disabled
        if: github.repository == 'RBniCS/ufl4rom' && github.ref == 'refs/heads/main' && github.event_name == 'schedule'
        uses: fem-on-colab/warn-workflow-about-to-be-disabled-action@main
        with:
          workflow-filename: ci.yml
          days-elapsed: 50
